export enum NotificationTypeEnum {
  ORDER = 'ORDER',
  USER_APPROVED = 'USER APPROVED',
  ASSET_PUBLISHED = 'ASSET PUBLISED',
  USER_REJECT = 'USER_REJECT',
  APPLICATION_SUBMITTED = 'APPLICATION SUBMITTED',
}
