/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "confirmEmail": string;
        "resetPassword": string;
    };
    "confirm-email": {
        "text1": string;
        "text2": string;
        "text3": string;
    };
    "confirm-new-email": {
        "text1": string;
        "text2": string;
        "text3": string;
    };
    "error-messages": {
        "already_exists": string;
        "incorrect": string;
        "incorrect_phone": string;
        "incorrect_email": string;
        "invalid_phone": string;
        "invalid_ocr_scan": string;
        "incorrect_credential": string;
        "not_present": string;
        "invalid_session": string;
        "user_not_found_with_valid_role": string;
        "invalid_phone_formate": string;
        "not_found": string;
        "not_found_without_value": string;
        "gen_ai_configuration_error": string;
        "not_following_error": string;
        "otp_verification_failed": string;
        "otp_sent_successfully": string;
        "already_following_error": string;
        "self_action_error": string;
        "user_id_required": string;
        "notification_fetch_error": string;
        "notification_id_required": string;
        "notification_update_error": string;
        "notification_mark_all_read_error": string;
        "notification_count_error": string;
        "article_not_favorite_error": string;
        "article_already_favorited_error": string;
        "enable_biometric_error": string;
        "disable_biometric_error": string;
        "biometric_challenge_error": string;
        "biometric_verification_failed": string;
        "error_biometric_verification": string;
        "password_criteria_failed": string;
        "user_document_unprocessable": string;
        "biometric_challenge_expiry": string;
        "method_not_found": string;
        "network_error": string;
        "technical_error": string;
        "invalid_credentials": string;
        "biometric_disabled": string;
        "credentials_not_found": string;
        "password_requirements": string;
        "invalid_full_name": string;
        "incorrect_password": string;
        "invalid_military_id": string;
        "invalid_email": string;
        "invalid_referral_code": string;
        "missing_fields": string;
        "face_scan_failed": string;
        "invalid_mykad": string;
        "store_location_unavailable": string;
        "no_search_results": string;
        "quantity_not_selected": string;
        "item_out_of_stock": string;
        "empty_cart": string;
        "not_allowed": string;
        "family_member": {
            "mykad_id_exists": string;
            "primary_member_exists": string;
            "user_with_mykad_exists": string;
            "user_with_phone_exists": string;
            "not_found": string;
            "primary_member_not_allowed": string;
            "member_not_created": string;
            "method_not_found": string;
        };
        "redis_configuration_error": string;
        "biometric_login_disabled": string;
        "internet_connection_error": string;
        "technical_difficulties": string;
        "phone_not_registered": string;
        "invalid_phone_number": string;
        "mandatory_fields_required": string;
        "no_results_found": string;
        "cart_empty": string;
        "category": {
            "method_not_found": string;
        };
    };
    "reset-password": {
        "text1": string;
        "text2": string;
        "text3": string;
        "text4": string;
    };
    "response-messages": {
        "user_registered": string;
        "password_set": string;
        "otp_verified": string;
        "forget_password": string;
        "pending_state": string;
        "password_updated": string;
        "profile_updated": string;
        "user_register_notification": string;
        "user_register_notification_title": string;
        "save_as_draft": string;
        "save_for_approval": string;
        "publish_now": string;
        "asset_approve_notification": string;
        "asset_status_update": string;
        "user_status_rejected": string;
        "user_status_approved": string;
        "user_status_resubmit": string;
        "user_status_title": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
