export enum FileType {
  SELFIE = 'SELFIE',
  ID_CARD = 'ID CARD',
  SALARY_SLIP = 'SALARY SLIP',
  BANK_STATEMENT = 'BANK STATEMENT',
  UTILITY_BILL = 'UTILITY BILL',
  PROFILE_IMAGE = 'PROFILE IMAGE',
}
