export const TABLES = {
  dashboard: 'dashboard',
  gcCmsUser: 'gc_cms_users',
  storeHoliday: 'store_holidays',
  gcCmsUserRole: 'gc_cms_user_roles',
  permissions: 'gc_cms_permissions',
  focusNewsCategories: 'focus_news_categories',
  rolePermissions: 'gc_cms_role_permissions',
  roles: 'gc_cms_roles',
  product: 'products',
  userStatusReasons: 'user_status_reasons',
  productCategory: 'product_category',
  productImage: 'product_images',
  inventory: 'inventory',
  cart: 'cart',
  cartItem: 'cart_items',
  notificationTokens: 'notification_tokens',
  order: 'orders',
  orderItem: 'order_items',
  biometricChallenge: 'biometric_challenges',
  biometric: 'biometric',
  governmentConnectMessage: 'government_connect_messages',
  familyMember: 'family_members',
  state: 'states',
  store: 'stores',
  cache: 'cache',
  razorPay: 'razorpay',
  razorPayTransactions: 'razorpay_transactions',
  logger: 'api_logger',
  armedForceBranch: 'armed_force_branches',
  category: 'categories',
  cmsUserCategory: 'gc_cms_user_categories',
  video: 'videos',
  messagePermissions: 'message_permissions',
  article: 'articles',
  encryption: 'encryption',
  otp: 'otp',
  gcCmsOtp: 'gc_cms_otp',
  file: 'files',
  session: 'sessions',
  gcCmsSession: 'gc_cms_sessions',
  user: 'users',
  userDevice: 'user_devices',
  notifications: 'notifications',
  gcCmsNotifications: 'gc_cms_notifications',
  gcCmsNotificationTokens: 'gc_cms_notification_tokens',
  eppRequest: 'epp_requests',
};

export const EVENTS = {
  userLoggedIn: 'user.loggedIn',
  userStatus: 'user.status',
  assetPublished: 'message.published',
  notifyGcCmsUser: 'notification.gcCmsuser',
};
